// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgeN-ehrQamUjgln2oop-21W_wNGjwkYM',
    appId: '1:497811681509:web:b38d2255018b652b11a40c',
    messagingSenderId: '497811681509',
    projectId: 'sketchtravel-6928a',
    authDomain: 'sketchtravel-6928a.firebaseapp.com',
    storageBucket: 'sketchtravel-6928a.firebasestorage.app',
    measurementId: 'G-SS3Q5C3NSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP6OvFjK6iImfMMbVFZ8wbZrG49mHLwEc',
    appId: '1:497811681509:android:26877f3dc26c72b511a40c',
    messagingSenderId: '497811681509',
    projectId: 'sketchtravel-6928a',
    storageBucket: 'sketchtravel-6928a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJHDXZnB8CzzBzy_Uw77iS8H6s5WKXSxQ',
    appId: '1:497811681509:ios:65ecae26d07116e811a40c',
    messagingSenderId: '497811681509',
    projectId: 'sketchtravel-6928a',
    storageBucket: 'sketchtravel-6928a.firebasestorage.app',
    iosBundleId: 'com.example.sketchTravel',
  );
}
